/**
 * fjm-api
 *  fjm-api is a service for monitoring the status of jobs submitted to our supercomputer. 
 *
 * OpenAPI spec version: 0.1.0
 * Contact: foo@bar.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */import { JobTimestamps } from './jobTimestamps';


/**
 * A record of a single job submission. When queried from its canonical endpoint (e.g. `/jobs/<jobID>`), all of this record's attributes are returned. When queried from a collections endpoint (e.g. `/jobs`), only the following attributes are returned:   * `ID`   * `name`   * `state`   * `timestamps`   * `URI` 
 */
export interface JobRecord { 
    /**
     * Unique identifier of the job.
     */
    ID?: string;
    /**
     * Absolute path to the working directory of the job. 
     */
    dir?: string;
    /**
     * Human readable name of the job.
     */
    name?: string;
    /**
     * Number of times the job has passed through the 'retrying' state. 
     */
    numRetried?: number;
    /**
     * Name of the project to which the job belongs.
     */
    projectName?: string;
    /**
     * State of this job.
     */
    state?: JobRecord.StateEnum;
    /**
     * Name of the user who submitted the job.
     */
    submitterName?: string;
    /**
     * Optional reason why the job state was set, may be null.
     */
    stateReason?: string;
    timestamps?: JobTimestamps;
    /**
     * URI pointing to the job record.
     */
    URI?: string;
}
export namespace JobRecord {
    export type StateEnum = 'submitted' | 'unknown' | 'running' | 'failed' | 'terminated' | 'successful';
    export const StateEnum = {
        Submitted: 'submitted' as StateEnum,
        Unknown: 'unknown' as StateEnum,
        Running: 'running' as StateEnum,
        Failed: 'failed' as StateEnum,
        Terminated: 'terminated' as StateEnum,
        Successful: 'successful' as StateEnum
    };
}