/**
 * fjm-api
 *  fjm-api is a service for monitoring the status of jobs submitted to our supercomputer. 
 *
 * OpenAPI spec version: 0.1.0
 * Contact: foo@bar.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

/**
 * Timestamps of various events related to the job record.
 */
export interface JobTimestamps { 
    /**
     * Time of last record modification.
     */
    lastModified?: Date;
    /**
     * Time of job submission.
     */
    submitted: Date;
    /**
     * Time when the cluster job comes out of the submit queue and starts to be processed. 
     */
    started?: Date;
    /**
     * Time when the cluster job stops being processed, either successfully or not. For this value to be non-null, the job must at least have passed through to the 'submitted' state. 
     */
    ended?: Date;
}